# Generated by Django 3.1.1 on 2020-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email_mobile',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='re_email_mobile',
        ),
        migrations.AddField(
            model_name='registration',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
