# Generated by Django 3.1.1 on 2020-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0002_auto_20201020_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
