# Generated by Django 3.1.1 on 2020-10-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0008_remove_userpost_friend_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='friend_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_post', to='facebook_app.friends'),
        ),
    ]
